apiVersion: v1
kind: Service
metadata:
  name: udacitycapstone-service
spec:
  selector:
    app: udacitycapstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
